name: MinimalTPA
version: '${version}'
main: net.cobaltonline.minimaltpa.MinimalTPA
api-version: 1.19
load: POSTWORLD
author: cobaltgit
description: A minimal TPA request plugin for Minecraft
website: https://github.com/cobaltgit/MinimalTPA
commands:
  tpa:
    description: Send a teleport request to another player
    usage: "Usage: /[tpa|tpask] <player>"
    aliases: [tpask]
    permission: minimaltpa.tpa
  tpaccept:
    description: Accept an incoming teleport request
    usage: "Usage: /tpaccept"
    permission: minimaltpa.tpaccept
  tpdeny:
    Description: Deny an incoming teleport request
    Usage: "Usage: /tpdeny"
    permission: minimaltpa.tpdeny
  tpcancel:
    description: Cancel an outgoing teleport request
    usage: "Usage: /tpcancel"
    permission: minimaltpa.tpcancel
  back:
    description: Go back to your previous location before sending an accepted teleport request
    usage: "Usage: /back"
    permission: minimaltpa.back

permissions:
  minimaltpa.*:
    description: Give operators all permissions
    default: op
  minimaltpa.tpa:
    description: Send TPA requests
    default: true
  minimaltpa.tpaccept:
    description: Accept an incoming TPA request
    default: true
  minimaltpa.tpdeny:
    description: Deny an incoming TPA request
    default: true
  minimaltpa.tpcancel:
    description: Cancel your current TPA request
    default: true
  minimaltpa.back:
    description: Go back to your previous location before sending a TPA or back request
    default: true
  minimaltpa.bypasscooldown:
    description: Bypass the TPA request and back command cooldown
    default: false